export default defineAppConfig({
  pages: [
    'pages/login/index',
    'pages/register/index',
    'pages/student/home/index',
    'pages/student/booking/index',
    'pages/student/tournament/index',
    'pages/student/profile/index',
    'pages/student/coaches/index',
    'pages/student/coaches/detail',
    'pages/student/my-tournaments/index',
    'pages/coach/home/index',
    'pages/coach/schedule/index',
    'pages/coach/students/index',
    'pages/coach/students/detail',
    'pages/coach/profile/index',
    'pages/admin/dashboard/index',
    'pages/admin/students/index',
    'pages/admin/coaches/index',
    'pages/admin/courses/index',
    'pages/admin/tournaments/index',
    'pages/admin/ntrp/index',
    'pages/admin/finance/index',
    'pages/admin/settings/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#1B4332',
    navigationBarTitleText: 'Tiger网球俱乐部',
    navigationBarTextStyle: 'white',
    backgroundColor: '#F5F5F5',
  },
  tabBar: {
    custom: true,
    color: '#BBBBBB',
    selectedColor: '#1B4332',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/student/home/index', text: '首页' },
      { pagePath: 'pages/student/booking/index', text: '约课' },
      { pagePath: 'pages/student/tournament/index', text: '赛事' },
      { pagePath: 'pages/student/profile/index', text: '我的' },
    ],
  },
})
